[[redirects]]
  from = "/search"
  to = "http://51.77.82.133:86/api/quotations/QUO_5fb3acb3a0f18"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}